CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Identity') THEN
        CREATE SCHEMA "Identity";
    END IF;
END $EF$;

CREATE TABLE "Identity"."Actors" (
    "ActorId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" character varying(255) NOT NULL,
    "Type" character varying(255) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DisplayName" character varying(255) NOT NULL,
    "EmailAddress" character varying(255),
    "PictureUrl" character varying(2048),
    CONSTRAINT "PK_Actors" PRIMARY KEY ("ActorId")
);

CREATE TABLE "Identity"."ApiKeys" (
    "ApiKeyId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255),
    "EntityId" character varying(255) NOT NULL,
    "SecretHash" character varying(255) NOT NULL,
    "DisplayName" character varying(255) NOT NULL,
    "Description" text,
    "ExpiresOn" timestamp with time zone,
    "AuthenticatedOn" timestamp with time zone,
    "CustomAttributes" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ApiKeys" PRIMARY KEY ("ApiKeyId")
);

CREATE TABLE "Identity"."CustomAttributes" (
    "CustomAttributeId" integer GENERATED BY DEFAULT AS IDENTITY,
    "EntityType" character varying(255) NOT NULL,
    "EntityId" integer NOT NULL,
    "Key" character varying(255) NOT NULL,
    "Value" text NOT NULL,
    "ValueShortened" character varying(255) NOT NULL,
    CONSTRAINT "PK_CustomAttributes" PRIMARY KEY ("CustomAttributeId")
);

CREATE TABLE "Identity"."OneTimePasswords" (
    "OneTimePasswordId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255),
    "EntityId" character varying(255) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL,
    "ExpiresOn" timestamp with time zone,
    "MaximumAttempts" integer,
    "AttemptCount" integer NOT NULL,
    "HasValidationSucceeded" boolean NOT NULL,
    "CustomAttributes" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_OneTimePasswords" PRIMARY KEY ("OneTimePasswordId")
);

CREATE TABLE "Identity"."Roles" (
    "RoleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255),
    "EntityId" character varying(255) NOT NULL,
    "UniqueName" character varying(255) NOT NULL,
    "UniqueNameNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255),
    "Description" text,
    "CustomAttributes" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("RoleId")
);

CREATE TABLE "Identity"."TokenBlacklist" (
    "BlacklistedTokenId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TokenId" character varying(255) NOT NULL,
    "ExpiresOn" timestamp with time zone,
    CONSTRAINT "PK_TokenBlacklist" PRIMARY KEY ("BlacklistedTokenId")
);

CREATE TABLE "Identity"."Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255),
    "EntityId" character varying(255) NOT NULL,
    "UniqueName" character varying(255) NOT NULL,
    "UniqueNameNormalized" character varying(255) NOT NULL,
    "PasswordHash" character varying(255),
    "PasswordChangedBy" character varying(255),
    "PasswordChangedOn" timestamp with time zone,
    "HasPassword" boolean NOT NULL,
    "DisabledBy" character varying(255),
    "DisabledOn" timestamp with time zone,
    "IsDisabled" boolean NOT NULL,
    "AddressStreet" character varying(255),
    "AddressLocality" character varying(255),
    "AddressPostalCode" character varying(255),
    "AddressRegion" character varying(255),
    "AddressCountry" character varying(255),
    "AddressFormatted" character varying(1279),
    "AddressVerifiedBy" character varying(255),
    "AddressVerifiedOn" timestamp with time zone,
    "IsAddressVerified" boolean NOT NULL,
    "EmailAddress" character varying(255),
    "EmailAddressNormalized" character varying(255),
    "EmailVerifiedBy" character varying(255),
    "EmailVerifiedOn" timestamp with time zone,
    "IsEmailVerified" boolean NOT NULL,
    "PhoneCountryCode" character varying(2),
    "PhoneNumber" character varying(20),
    "PhoneExtension" character varying(10),
    "PhoneE164Formatted" character varying(40),
    "PhoneVerifiedBy" character varying(255),
    "PhoneVerifiedOn" timestamp with time zone,
    "IsPhoneVerified" boolean NOT NULL,
    "IsConfirmed" boolean NOT NULL,
    "FirstName" character varying(255),
    "MiddleName" character varying(255),
    "LastName" character varying(255),
    "FullName" character varying(767),
    "Nickname" character varying(255),
    "Birthdate" timestamp with time zone,
    "Gender" character varying(255),
    "Locale" character varying(16),
    "TimeZone" character varying(32),
    "Picture" character varying(2048),
    "Profile" character varying(2048),
    "Website" character varying(2048),
    "AuthenticatedOn" timestamp with time zone,
    "CustomAttributes" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);

CREATE TABLE "Identity"."ApiKeyRoles" (
    "ApiKeyId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_ApiKeyRoles" PRIMARY KEY ("ApiKeyId", "RoleId"),
    CONSTRAINT "FK_ApiKeyRoles_ApiKeys_ApiKeyId" FOREIGN KEY ("ApiKeyId") REFERENCES "Identity"."ApiKeys" ("ApiKeyId") ON DELETE CASCADE,
    CONSTRAINT "FK_ApiKeyRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Identity"."Roles" ("RoleId") ON DELETE CASCADE
);

CREATE TABLE "Identity"."Sessions" (
    "SessionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255),
    "EntityId" character varying(255) NOT NULL,
    "UserId" integer NOT NULL,
    "SecretHash" character varying(255),
    "IsPersistent" boolean NOT NULL,
    "SignedOutBy" character varying(255),
    "SignedOutOn" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "CustomAttributes" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Sessions" PRIMARY KEY ("SessionId"),
    CONSTRAINT "FK_Sessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Identity"."Users" ("UserId") ON DELETE RESTRICT
);

CREATE TABLE "Identity"."UserIdentifiers" (
    "UserIdentifierId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "TenantId" character varying(255),
    "Key" character varying(255) NOT NULL,
    "Value" character varying(255) NOT NULL,
    CONSTRAINT "PK_UserIdentifiers" PRIMARY KEY ("UserIdentifierId"),
    CONSTRAINT "FK_UserIdentifiers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Identity"."Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Identity"."UserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Identity"."Roles" ("RoleId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Identity"."Users" ("UserId") ON DELETE CASCADE
);

CREATE INDEX "IX_Actors_DisplayName" ON "Identity"."Actors" ("DisplayName");

CREATE INDEX "IX_Actors_EmailAddress" ON "Identity"."Actors" ("EmailAddress");

CREATE UNIQUE INDEX "IX_Actors_Id" ON "Identity"."Actors" ("Id");

CREATE INDEX "IX_Actors_IsDeleted" ON "Identity"."Actors" ("IsDeleted");

CREATE INDEX "IX_Actors_Type" ON "Identity"."Actors" ("Type");

CREATE INDEX "IX_ApiKeyRoles_RoleId" ON "Identity"."ApiKeyRoles" ("RoleId");

CREATE INDEX "IX_ApiKeys_AuthenticatedOn" ON "Identity"."ApiKeys" ("AuthenticatedOn");

CREATE INDEX "IX_ApiKeys_CreatedBy" ON "Identity"."ApiKeys" ("CreatedBy");

CREATE INDEX "IX_ApiKeys_CreatedOn" ON "Identity"."ApiKeys" ("CreatedOn");

CREATE INDEX "IX_ApiKeys_DisplayName" ON "Identity"."ApiKeys" ("DisplayName");

CREATE INDEX "IX_ApiKeys_EntityId" ON "Identity"."ApiKeys" ("EntityId");

CREATE INDEX "IX_ApiKeys_ExpiresOn" ON "Identity"."ApiKeys" ("ExpiresOn");

CREATE UNIQUE INDEX "IX_ApiKeys_StreamId" ON "Identity"."ApiKeys" ("StreamId");

CREATE UNIQUE INDEX "IX_ApiKeys_TenantId_EntityId" ON "Identity"."ApiKeys" ("TenantId", "EntityId");

CREATE INDEX "IX_ApiKeys_UpdatedBy" ON "Identity"."ApiKeys" ("UpdatedBy");

CREATE INDEX "IX_ApiKeys_UpdatedOn" ON "Identity"."ApiKeys" ("UpdatedOn");

CREATE INDEX "IX_ApiKeys_Version" ON "Identity"."ApiKeys" ("Version");

CREATE INDEX "IX_CustomAttributes_EntityType_EntityId" ON "Identity"."CustomAttributes" ("EntityType", "EntityId");

CREATE UNIQUE INDEX "IX_CustomAttributes_EntityType_EntityId_Key" ON "Identity"."CustomAttributes" ("EntityType", "EntityId", "Key");

CREATE INDEX "IX_CustomAttributes_Key" ON "Identity"."CustomAttributes" ("Key");

CREATE INDEX "IX_CustomAttributes_ValueShortened" ON "Identity"."CustomAttributes" ("ValueShortened");

CREATE INDEX "IX_OneTimePasswords_AttemptCount" ON "Identity"."OneTimePasswords" ("AttemptCount");

CREATE INDEX "IX_OneTimePasswords_CreatedBy" ON "Identity"."OneTimePasswords" ("CreatedBy");

CREATE INDEX "IX_OneTimePasswords_CreatedOn" ON "Identity"."OneTimePasswords" ("CreatedOn");

CREATE INDEX "IX_OneTimePasswords_EntityId" ON "Identity"."OneTimePasswords" ("EntityId");

CREATE INDEX "IX_OneTimePasswords_ExpiresOn" ON "Identity"."OneTimePasswords" ("ExpiresOn");

CREATE INDEX "IX_OneTimePasswords_HasValidationSucceeded" ON "Identity"."OneTimePasswords" ("HasValidationSucceeded");

CREATE INDEX "IX_OneTimePasswords_MaximumAttempts" ON "Identity"."OneTimePasswords" ("MaximumAttempts");

CREATE UNIQUE INDEX "IX_OneTimePasswords_StreamId" ON "Identity"."OneTimePasswords" ("StreamId");

CREATE UNIQUE INDEX "IX_OneTimePasswords_TenantId_EntityId" ON "Identity"."OneTimePasswords" ("TenantId", "EntityId");

CREATE INDEX "IX_OneTimePasswords_UpdatedBy" ON "Identity"."OneTimePasswords" ("UpdatedBy");

CREATE INDEX "IX_OneTimePasswords_UpdatedOn" ON "Identity"."OneTimePasswords" ("UpdatedOn");

CREATE INDEX "IX_OneTimePasswords_Version" ON "Identity"."OneTimePasswords" ("Version");

CREATE INDEX "IX_Roles_CreatedBy" ON "Identity"."Roles" ("CreatedBy");

CREATE INDEX "IX_Roles_CreatedOn" ON "Identity"."Roles" ("CreatedOn");

CREATE INDEX "IX_Roles_DisplayName" ON "Identity"."Roles" ("DisplayName");

CREATE INDEX "IX_Roles_EntityId" ON "Identity"."Roles" ("EntityId");

CREATE UNIQUE INDEX "IX_Roles_StreamId" ON "Identity"."Roles" ("StreamId");

CREATE UNIQUE INDEX "IX_Roles_TenantId_EntityId" ON "Identity"."Roles" ("TenantId", "EntityId");

CREATE UNIQUE INDEX "IX_Roles_TenantId_UniqueNameNormalized" ON "Identity"."Roles" ("TenantId", "UniqueNameNormalized");

CREATE INDEX "IX_Roles_UniqueName" ON "Identity"."Roles" ("UniqueName");

CREATE INDEX "IX_Roles_UpdatedBy" ON "Identity"."Roles" ("UpdatedBy");

CREATE INDEX "IX_Roles_UpdatedOn" ON "Identity"."Roles" ("UpdatedOn");

CREATE INDEX "IX_Roles_Version" ON "Identity"."Roles" ("Version");

CREATE INDEX "IX_Sessions_CreatedBy" ON "Identity"."Sessions" ("CreatedBy");

CREATE INDEX "IX_Sessions_CreatedOn" ON "Identity"."Sessions" ("CreatedOn");

CREATE INDEX "IX_Sessions_EntityId" ON "Identity"."Sessions" ("EntityId");

CREATE INDEX "IX_Sessions_IsActive" ON "Identity"."Sessions" ("IsActive");

CREATE INDEX "IX_Sessions_IsPersistent" ON "Identity"."Sessions" ("IsPersistent");

CREATE INDEX "IX_Sessions_SignedOutBy" ON "Identity"."Sessions" ("SignedOutBy");

CREATE INDEX "IX_Sessions_SignedOutOn" ON "Identity"."Sessions" ("SignedOutOn");

CREATE UNIQUE INDEX "IX_Sessions_StreamId" ON "Identity"."Sessions" ("StreamId");

CREATE UNIQUE INDEX "IX_Sessions_TenantId_EntityId" ON "Identity"."Sessions" ("TenantId", "EntityId");

CREATE INDEX "IX_Sessions_UpdatedBy" ON "Identity"."Sessions" ("UpdatedBy");

CREATE INDEX "IX_Sessions_UpdatedOn" ON "Identity"."Sessions" ("UpdatedOn");

CREATE INDEX "IX_Sessions_UserId" ON "Identity"."Sessions" ("UserId");

CREATE INDEX "IX_Sessions_Version" ON "Identity"."Sessions" ("Version");

CREATE INDEX "IX_TokenBlacklist_ExpiresOn" ON "Identity"."TokenBlacklist" ("ExpiresOn");

CREATE UNIQUE INDEX "IX_TokenBlacklist_TokenId" ON "Identity"."TokenBlacklist" ("TokenId");

CREATE INDEX "IX_UserIdentifiers_Key" ON "Identity"."UserIdentifiers" ("Key");

CREATE UNIQUE INDEX "IX_UserIdentifiers_TenantId_Key_Value" ON "Identity"."UserIdentifiers" ("TenantId", "Key", "Value");

CREATE UNIQUE INDEX "IX_UserIdentifiers_UserId_Key" ON "Identity"."UserIdentifiers" ("UserId", "Key");

CREATE INDEX "IX_UserIdentifiers_Value" ON "Identity"."UserIdentifiers" ("Value");

CREATE INDEX "IX_UserRoles_RoleId" ON "Identity"."UserRoles" ("RoleId");

CREATE INDEX "IX_Users_AddressCountry" ON "Identity"."Users" ("AddressCountry");

CREATE INDEX "IX_Users_AddressFormatted" ON "Identity"."Users" ("AddressFormatted");

CREATE INDEX "IX_Users_AddressLocality" ON "Identity"."Users" ("AddressLocality");

CREATE INDEX "IX_Users_AddressPostalCode" ON "Identity"."Users" ("AddressPostalCode");

CREATE INDEX "IX_Users_AddressRegion" ON "Identity"."Users" ("AddressRegion");

CREATE INDEX "IX_Users_AddressStreet" ON "Identity"."Users" ("AddressStreet");

CREATE INDEX "IX_Users_AddressVerifiedBy" ON "Identity"."Users" ("AddressVerifiedBy");

CREATE INDEX "IX_Users_AddressVerifiedOn" ON "Identity"."Users" ("AddressVerifiedOn");

CREATE INDEX "IX_Users_AuthenticatedOn" ON "Identity"."Users" ("AuthenticatedOn");

CREATE INDEX "IX_Users_Birthdate" ON "Identity"."Users" ("Birthdate");

CREATE INDEX "IX_Users_CreatedBy" ON "Identity"."Users" ("CreatedBy");

CREATE INDEX "IX_Users_CreatedOn" ON "Identity"."Users" ("CreatedOn");

CREATE INDEX "IX_Users_DisabledBy" ON "Identity"."Users" ("DisabledBy");

CREATE INDEX "IX_Users_DisabledOn" ON "Identity"."Users" ("DisabledOn");

CREATE INDEX "IX_Users_EmailAddress" ON "Identity"."Users" ("EmailAddress");

CREATE INDEX "IX_Users_EmailVerifiedBy" ON "Identity"."Users" ("EmailVerifiedBy");

CREATE INDEX "IX_Users_EmailVerifiedOn" ON "Identity"."Users" ("EmailVerifiedOn");

CREATE INDEX "IX_Users_EntityId" ON "Identity"."Users" ("EntityId");

CREATE INDEX "IX_Users_FirstName" ON "Identity"."Users" ("FirstName");

CREATE INDEX "IX_Users_FullName" ON "Identity"."Users" ("FullName");

CREATE INDEX "IX_Users_Gender" ON "Identity"."Users" ("Gender");

CREATE INDEX "IX_Users_HasPassword" ON "Identity"."Users" ("HasPassword");

CREATE INDEX "IX_Users_IsAddressVerified" ON "Identity"."Users" ("IsAddressVerified");

CREATE INDEX "IX_Users_IsConfirmed" ON "Identity"."Users" ("IsConfirmed");

CREATE INDEX "IX_Users_IsDisabled" ON "Identity"."Users" ("IsDisabled");

CREATE INDEX "IX_Users_IsEmailVerified" ON "Identity"."Users" ("IsEmailVerified");

CREATE INDEX "IX_Users_IsPhoneVerified" ON "Identity"."Users" ("IsPhoneVerified");

CREATE INDEX "IX_Users_LastName" ON "Identity"."Users" ("LastName");

CREATE INDEX "IX_Users_Locale" ON "Identity"."Users" ("Locale");

CREATE INDEX "IX_Users_MiddleName" ON "Identity"."Users" ("MiddleName");

CREATE INDEX "IX_Users_Nickname" ON "Identity"."Users" ("Nickname");

CREATE INDEX "IX_Users_PasswordChangedBy" ON "Identity"."Users" ("PasswordChangedBy");

CREATE INDEX "IX_Users_PasswordChangedOn" ON "Identity"."Users" ("PasswordChangedOn");

CREATE INDEX "IX_Users_PhoneCountryCode" ON "Identity"."Users" ("PhoneCountryCode");

CREATE INDEX "IX_Users_PhoneE164Formatted" ON "Identity"."Users" ("PhoneE164Formatted");

CREATE INDEX "IX_Users_PhoneExtension" ON "Identity"."Users" ("PhoneExtension");

CREATE INDEX "IX_Users_PhoneNumber" ON "Identity"."Users" ("PhoneNumber");

CREATE INDEX "IX_Users_PhoneVerifiedBy" ON "Identity"."Users" ("PhoneVerifiedBy");

CREATE INDEX "IX_Users_PhoneVerifiedOn" ON "Identity"."Users" ("PhoneVerifiedOn");

CREATE UNIQUE INDEX "IX_Users_StreamId" ON "Identity"."Users" ("StreamId");

CREATE INDEX "IX_Users_TenantId_EmailAddressNormalized" ON "Identity"."Users" ("TenantId", "EmailAddressNormalized");

CREATE UNIQUE INDEX "IX_Users_TenantId_EntityId" ON "Identity"."Users" ("TenantId", "EntityId");

CREATE UNIQUE INDEX "IX_Users_TenantId_UniqueNameNormalized" ON "Identity"."Users" ("TenantId", "UniqueNameNormalized");

CREATE INDEX "IX_Users_TimeZone" ON "Identity"."Users" ("TimeZone");

CREATE INDEX "IX_Users_UniqueName" ON "Identity"."Users" ("UniqueName");

CREATE INDEX "IX_Users_UpdatedBy" ON "Identity"."Users" ("UpdatedBy");

CREATE INDEX "IX_Users_UpdatedOn" ON "Identity"."Users" ("UpdatedOn");

CREATE INDEX "IX_Users_Version" ON "Identity"."Users" ("Version");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241223001722_Release_3_0_0', '9.0.0');

COMMIT;
